### ISSUE TITLE
The module can't find "~/Grapycal/backend/src/grapycal/webpage

### ISSUE THREAD

**Issue by haoiyang** [eri24816/Grapycal#12]
Hi, I am very interested in this project.
However, after running 'python3 -m grapycal', the module fails and displays the following error:

FileNotFoundError: [Errno 2] No such file or directory: '~/Grapycal/backend/src/grapycal/webpage'

I checked the directory and found no webpage there.
What should I do to resolve this issue?
Thank you.

**Comment by eri24816** [comment]
Hi. Thank you for trying out the project!

It's my fault causing the issue. To make Grapycal run correctly, there should be a `webpage` folder containing the webpage resources for Grapycal e.g. `index.html` and `main.js`, but I did not push it to this repo, which causes the error you got. I'll fix it ASAP.

A quick workaround is: 
1. Download [webpage.zip](https://github.com/eri24816/Grapycal/files/13400969/webpage.zip), extract it, and put it under `Grapycal\backend\src\grapycal\`

2. Update the content of the repo.

```
cd Grapycal
git pull https://github.com/eri24816/Grapycal.git
cd backend
pip install -e .
```

3. Now  `python -m grapycal` should run successfully.

**Comment by eri24816** [comment]
Also, feel free to join [our Discord server ](https://discord.gg/pweJ9H5H) for more real time discussions.

**Comment by haoiyang** [comment]
Hi, it seems to be functioning now. Thank you.
